import assert from 'assert'
import am from '../am'
import './wrapping'
import './map'
import './mapFilter'
import './filter'
import './forEach'
import './next'
import './error'
import './then'
import './catch'
import './promise'
import './prev'
import './wait'
import './timeout'
import './log'
