import assert from 'assert'
import am from 'async-methods'
import './wrapping'
import './map'
import './mapFilter'
import './filter'
import './forEach'
import './next'
import './then'
import './catch'
import './promise'
